name: CI

on: pull_request

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install Dependencies
        run: npm ci

      - name: Formatting
        run: npm run format

      - name: Linting
        run: npm run lint

      - name: Test
        run: npm run test
